version: '3'
volumes:
    db-vol:
services:
    api:
        image: penum:api
        build: ./api
        ports:
            - "5000:5000"
    web:
        image: penum:www
        build: ./www
        environment:
            - API_ENDPOINT=http://api:5000
        ports:
            - "8080:8080"
        volumes:
            - ./www/src:/var/www
    db:
        image: penum:psql
        build: ./psql
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: penum
        ports:
            - "5432:5432"
        volumes:
            - db-vol:/var/lib/postgresql/data
    amass:
        image: penum:amass
        build: ./tools/subdomain/amass
        working_dir: /
        ports:
            - "30000"
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    subfinder:
        image: penum:subfinder
        build: ./tools/subdomain/subfinder
        working_dir: /
        ports:
            - "30001"
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    aiodnsbrute:
        image: penum:aiodnsbrute
        build: ./tools/subdomain/aiodnsbrute
        working_dir: /
        ports:
            - "30002"
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    sublist3r:
        image: penum:sublist3r
        build: ./tools/subdomain/sublist3r
        working_dir: /
        ports:
            - "30003"
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    gobuster:
        image: penum:gobuster
        build: ./tools/subdomain/gobuster
        working_dir: /
        ports:
            - "30004"
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    massdns:
        image: penum:massdns
        build: ./tools/subdomain/massdns
        working_dir: /
        ports:
            - "30005"
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    aquatone:
        image: penum:aquatone
        build: ./tools/http/aquatone
        working_dir: /
        ports:
            - "30006"
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    nmap:
        image: penum:nmap
        build: ./tools/network/nmap
        working_dir: /
        ports:
            - "30007"
        entrypoint: /etc/run_xinetd.sh
        read_only: false


