version: '3'
services:
    api:
        image: penum:api
        build: ./api
        ports:
            - "5000:5000"
    amass:
        image: penum:amass
        build: ./amass
        working_dir: /
        ports:
            - "30000:30000" # exposed:local
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    subfinder:
        image: penum:subfinder
        build: ./subfinder
        working_dir: /
        ports:
            - "30001:30001" # exposed:local
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    aiodnsbrute:
        image: penum:aiodnsbrute
        build: ./aiodnsbrute
        working_dir: /
        ports:
            - "30002:30002" # exposed:local
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    sublist3r:
        image: penum:sublist3r
        build: ./sublist3r
        working_dir: /
        ports:
            - "30003:30003" # exposed:local
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    gobuster:
        image: penum:gobuster
        build: ./gobuster
        working_dir: /
        ports:
            - "30004:30004" # exposed:local
        entrypoint: /etc/run_xinetd.sh
        read_only: false
    massdns:
        image: penum:massdns
        build: ./massdns
        working_dir: /
        ports:
            - "30005:30005" # exposed:local
        entrypoint: /etc/run_xinetd.sh
        read_only: false

